answer = int(input("Give a whole number that is less than 8.\n"))
print(answer < 8)
answer_2 = int(input("Give a whole number more then or equal to 10. \n"))
print(answer_2 >= 10)
answer_3 = int(input("Give a whole number equal to 2. \n"))
print(answer_3 == 2)
answer_4 = int(input("Give a whole number more than 20. \n"))
print(answer_4 > 20)
answer_5 = int(input("Give a whole number less than or equal to 9. \n"))
print(answer_5 <= 9) 