user_input1 = input("what is your favorite animal: ")
user_input2 = input("what color is the chipmink: ")
user_input3 = input("where is the chipmunk found: ")
user_input4 = input("why do you like that animal: ")
print("what is your favorite animal " +  user_input1  + " what color is the chipmunk " + user_input2 + " where is the chipmunk found " + user_input3 + " why do you like the animal ")